"""Add documents field to worker profiles

Revision ID: e55b82302ea2
Revises: cba5aeeeabce
Create Date: 2025-11-22 15:09:30.271971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55b82302ea2'
down_revision: Union[str, None] = 'cba5aeeeabce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_profiles', sa.Column('documents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'documents')
    # ### end Alembic commands ###
