"""Add applications table and remove employer photo_url

Revision ID: 5b656febdfb2
Revises: 7392c259d20f
Create Date: 2025-11-22 14:47:19.775438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b656febdfb2'
down_revision: Union[str, None] = '7392c259d20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_profiles', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'photo_url')
    # ### end Alembic commands ###
