"""Fix ARRAY defaults and add indexes for profiles

Revision ID: 23f0ad9b9e61
Revises: 7a10d2f42408
Create Date: 2025-11-22 14:03:14.189777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23f0ad9b9e61'
down_revision: Union[str, None] = '7a10d2f42408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employer_profiles', 'radius_km',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employer_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('employer_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('employer_profiles_user_id_key', 'employer_profiles', type_='unique')
    op.create_index(op.f('ix_employer_profiles_user_id'), 'employer_profiles', ['user_id'], unique=True)
    op.alter_column('worker_profiles', 'radius_km',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('worker_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('worker_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('worker_profiles_user_id_key', 'worker_profiles', type_='unique')
    op.create_index(op.f('ix_worker_profiles_user_id'), 'worker_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_profiles_user_id'), table_name='worker_profiles')
    op.create_unique_constraint('worker_profiles_user_id_key', 'worker_profiles', ['user_id'])
    op.alter_column('worker_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('worker_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('worker_profiles', 'radius_km',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_employer_profiles_user_id'), table_name='employer_profiles')
    op.create_unique_constraint('employer_profiles_user_id_key', 'employer_profiles', ['user_id'])
    op.alter_column('employer_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('employer_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('employer_profiles', 'radius_km',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
